app.py
from flask import Flask
import json
from .blueprintname import blueprintname
from .cache import cache

# TODO: Update blueprintname

app = Flask(__name__)
cache.init_app(app, config={'CACHE_TYPE': 'SimpleCache'})
app.register_blueprint(blueprintname, url_prefix='/')
app.config.from_file("config.json", load=json.load)

if __name__ == '__main__':
    app.run(host='0.0.0.0')

blueprintname.py
from flask import Blueprint, render_template, current_app
from .cache import cache

blueprintname = Blueprint("blueprintname", __name__, template_folder="templates", static_folder="static")


def get_attribution():
    return current_app.config['ATTRIBUTION']

def get_app_config():
    return current_app.config['APPS']['blueprintname']


@blueprintname.route("/")
@cache.cached(timeout=300)
async def home():

    # DO STUFF...

    return render_template("_home.html", app=get_app_config(), attribution=get_attribution())

templates/_home.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{ app.title }}</title>
  <meta name="theme-color" content="#3054bf">
  <meta name="description" content="{{ app.description  }}" />
  <meta property="og:description" content="{{ app.description }}" />
  <meta name="author" content="{{ attribution.owner }}" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="{{ app.site_name }}" />
  <meta property="og:title" content="{{ app.title }}" />

  <style>
    html {
      scroll-behavior: smooth;
    }

    body {
      font-family: system-ui, sans-serif;
      max-width: 600px;
      margin: 0 auto;
      color: var(--text-color-dark);
      font-size: var(--font-size-base);
      display: grid;
      gap: 1em;
      padding: 0 1em;

      a {
        color: var(--color-link);
      }

      small {
        font-size: var(--font-size-sm);
      }
    }

    header {
      & a.app-title {
        text-decoration: none;

        &:hover {
          text-decoration: underline;
        }
      }
    }

    header,
    footer {
      background: var(--ayo-gradient);
      color: var(--text-color-light);
      border-radius: 5px;
      padding: 1em;
      text-wrap: balance;

      & a {
        color: var(--text-color-light);
      }
    }

    footer {
      border-bottom-left-radius: 0;
      border-bottom-right-radius: 0;
    }

    main {
      & ul.tags {
        list-style: none;
        padding-left: 0;

        & li {
          display: inline
        }
      }
    }

    main {
      display: grid;
      gap: 1em;
    }

    main.home {
      & .back {
        display: none
      }
    }

    main.thread {
      & .card:not(:last-of-type) .card_avatar::after {
        content: " ";
        display: block;
        height: 100%;
        border-right: 2px solid rgba(34, 34, 34, 0.15);
        width: 26px;
        margin-top: -8px;
      }
    }

    .card_avatar img {
      border: 2px solid rgba(197, 209, 222, 0.15);
      border-radius: 50%;
      display: inline;
      width: 50px;
    }

    .card {
      grid-template-columns: 55px auto;
      display: grid;
      gap: 5px;
    }

    @media (prefers-color-scheme: dark) {

      html,
      body {
        background: var(--bg-darker);
        color: var(--text-color-light);
      }

      main a {
        color: var(--color-brand-complement);
      }

      main.thread {
        & .card:not(:last-of-type) .card_avatar::after {
          border-right: 2px solid rgba(197, 209, 222, 0.15);
        }
      }

    }
  </style>

  <!-- Use parent app's variables & reset stylesheets -->
  <link rel="stylesheet" href="{{ url_for('static', filename='variables.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='reset.css') }}" />

</head>

<body>
  <a id="top"></a>
  <header>
    {% include "nav.html" %}
    <a class="app-title" href="{{url_for('blueprintname.home')}}">
      <h1>{{ app.title }}</h1>
    </a>
    <p>{{ app.description }}</p>

  </header>
  <main>
    <p>CONTENT GOES HERE</p>
  </main>
  <footer>
    <p>
      Copyright &copy;
      {% if attribution.current_year %}
      {{ attribution.year}}-{{ attribution.current_year }}
      {% else %}
      {{ attribution.year}}
      {% endif %}
      {{ attribution.owner }}
    </p>
  </footer>
</body>

</html>

templates/nav.html
<nav><a href="/">Go home</a></nav>